// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzb51hA86wEDHLGeEEgvYNGe2LqqFMok',
    appId: '1:885265811986:web:71941454cb19a481b0e6cb',
    messagingSenderId: '885265811986',
    projectId: 'tcckau',
    authDomain: 'tcckau.firebaseapp.com',
    storageBucket: 'tcckau.appspot.com',
    measurementId: 'G-HQSVFWSCL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcOjoEBLYfWCEU3IpIqL0tFY7_f2SJgA',
    appId: '1:885265811986:android:03b1385234798cfab0e6cb',
    messagingSenderId: '885265811986',
    projectId: 'tcckau',
    storageBucket: 'tcckau.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_q-N0CPpIT60z1uXjOj289y0i5EG-MNY',
    appId: '1:885265811986:ios:6df36a38f58ad942b0e6cb',
    messagingSenderId: '885265811986',
    projectId: 'tcckau',
    storageBucket: 'tcckau.appspot.com',
    iosClientId: '885265811986-nu374aiudtd3a1dcssbtrhsrvuecsoo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcckau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_q-N0CPpIT60z1uXjOj289y0i5EG-MNY',
    appId: '1:885265811986:ios:6df36a38f58ad942b0e6cb',
    messagingSenderId: '885265811986',
    projectId: 'tcckau',
    storageBucket: 'tcckau.appspot.com',
    iosClientId: '885265811986-nu374aiudtd3a1dcssbtrhsrvuecsoo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcckau',
  );
}
